export default function DadosVagas() {
    const vagas = [
      { id: '1', titulo: 'Jovem Aprendiz/Auxiliar',
        cargaHoraria: '20h semanais/Segunda a sexta, 13h às 17h',
        salario: 'A negociar',
        idade: '14 a 22 anos',
        escolaridade:'Cursando ou concluído o ensino médio',
        requisitos:'Conhecimentos básicos de informática; Boa comunicação; Responsabilidade e vontade de aprender',
        beneficios:'Vale transporte; Vale alimentação; Seguro de vida;',
        topicos:[
          {descricao: '- Auxiliar na organização de documentos'},
          {descricao: '- Apoiar a equipe nas tarefas do dia a dia'},
          {descricao: '- Preencher planilhas e cadastrar informações'},
          {descricao: '- Aprender novas atividades administrativas'},
        ] },
      { id: '2', titulo: 'Vendedor Interno', 
        cargaHoraria: '44h semanais/Segunda a sexta, 8h às 17h48, e sábados alternados',
        salario: 'Fixo + comissão (valor a combinar)',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino médio completo',
        requisitos: 'Desejável experiência em atendimento ou em vendas',
        beneficios: 'Vale transporte; Seguro de vida; Plano de saúde;',
        topicos:[
          {descricao: '- Atendimento ao cliente presencialmente, por telefone e por whatsapp'},
          {descricao: '- Apresentar produtos e esclarecer dúvidas,'},
          {descricao: '- Elaborar orçamentos e registrar pedidos'},
          {descricao: '- Manter o cadastro de clientes atualizado'},
          {descricao: '- Cumprir metas de vendas definidas pela empresa'},
        ] },
      { id: '3', titulo: 'Auxiliar de Produção', 
        cargaHoraria: '44h semanais/Segunda a sexta, 7h30 às 17h18 (turno administrativo)',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino fundamental completo (ensino médio desejável)',
        requisitos: 'Desejável experiência em produção ou em linha de montagem',
        beneficios: 'Vale transporte; Vale alimentação; Seguro de vida;',
        topicos:[
          {descricao: '- Abastecer as linhas de produção com materiais e insumos'},
          {descricao: '- Operar máquinas e equipamentos simples, após treinamento'},
          {descricao: '- Realizar inspeção de qualidade nos produtos'},
          {descricao: '- Auxiliar na embalagem e expedição dos produtos'},
          {descricao: '- Seguir normas de segurança e higiene no ambiente de trabalho'}
        ] },
      { id: '4', titulo: 'Auxiliar de RH', 
        cargaHoraria: '40h semanais/Segunda a sexta, 8h às 17h',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino médio completo (cursando graduação em RH ou Administração é um diferencial)',
        requisitos: 'Desejável experiência em recursos humanos',
        beneficios: 'Vale transporte',
        topicos:[
          {descricao: '- Apoiar o processo de recrutamento e seleção'},
          {descricao: '- Agendar entrevistas e acompanhar candidatos'},
          {descricao: '- Auxiliar na administração de benefícios e folha de pagamento'},
          {descricao: '- Manter registros e arquivos atualizados'},
          {descricao: '- Colaborar com a equipe de RH em projetos e atividades diversas'}
        ] },
      { id: '5', titulo: 'Auxiliar Administrativo', 
        cargaHoraria: '44h semanais/Segunda a sexta, 8h às 17h',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino médio completo',
        requisitos: 'Informática básica (pacote Office ou Google)',
        beneficios:'não informado',
        topicos:[
          {descricao: '- Organizar e arquivar documentos físicos e digitais'},
          {descricao: '- Atender chamadas telefônicas e responder e-mails'},
          {descricao: '- Auxiliar na elaboração de relatórios e planilhas'},
          {descricao: '- Controlar o estoque de materiais de escritório'},
          {descricao: '- Apoiar a equipe em tarefas administrativas diversas'}
        ] },
      { id: '6', titulo: 'Fiscal de Caixa', 
        cargaHoraria: '44h semanais/Escala 6x1, em turnos (manhã ou tarde)',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino médio completo)',
        requisitos: 'Conhecimento básico de sistemas de PDV',
        beneficios: 'Vale alimentação',
        topicos:[
          {descricao: '- Operar o caixa registrador e processar transações de vendas'},
          {descricao: '- Verificar a autenticidade de notas e moedas'},
          {descricao: '- Emitir recibos e notas fiscais'},
          {descricao: '- Manter o caixa organizado e reconciliar o dinheiro no final do turno'},
          {descricao: '- Atender clientes com cortesia e resolver problemas de pagamento'}
        ] },
      { id: '7', titulo: 'Repositor de Mercadorias', 
        cargaHoraria: '44h semanais/Escala 6x1, em turnos (manhã ou tarde)',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino fundamental completo',
        requisitos: 'Desejável experiência em supermercado ou varejo, mas não obrigatória',
        beneficios: 'Uniforme fornecido pela empresa',
        topicos:[
          {descricao: ' - Repor produtos nas prateleiras e gôndolas'},
          {descricao: '- Verificar datas de validade e organizar produtos de acordo com as normas da empresa'},
          {descricao: '- Auxiliar na conferência de mercadorias recebidas e no controle de estoque'},
          {descricao: '- Manter a área de trabalho limpa e organizada'},
          {descricao: '- Atender clientes e fornecer informações sobre produtos, quando necessário'}
        ] },
      { id: '8', titulo: 'Empacotador', 
        cargaHoraria: '44h semanais/Escala 6x1, em turnos (manhã ou tarde)',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino fundamental completo',
        requisitos: 'Desejável experiência em empacotamento',
        beneficios: 'Uniforme fornecido pela empresa',
        topicos:[
          {descricao: '- Empacotar produtos de forma eficiente e segura'},
          {descricao: '- Manter a área de empacotamento limpa e organizada'},
          {descricao: '- Auxiliar clientes com o empacotamento de suas compras, quando necessário'},
          {descricao: '- Seguir normas de segurança e higiene no ambiente de trabalho'},
          {descricao: '- Colaborar com a equipe para garantir um fluxo de trabalho eficiente'}
        ] },
      { id: '9', titulo: 'Auxiliar de Cozinha', 
        cargaHoraria: '44h semanais/Escala 6x1, em turnos (manhã ou tarde)',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino médio completo',
        requisitos: 'Não é necessário, a empresa treina o candidato',
        beneficios: 'alimentação no local; Uniforme fornecido pela empresa',
        topicos:[
          {descricao: '- Auxiliar na preparação de alimentos, seguindo receitas e padrões de qualidade'},
          {descricao: '- Manter a cozinha limpa e organizada, lavando utensílios e equipamentos'},
          {descricao: '- Controlar o estoque de ingredientes e informar a necessidade de reposição'},
          {descricao: '- Seguir normas de segurança alimentar e higiene pessoal'},
          {descricao: '- Colaborar com a equipe para garantir um serviço eficiente e de qualidade'}
        ] },
      { id: '10', titulo: 'Auxiliar de Serviços Gerais', 
        cargaHoraria: '44h semanais/Segunda a sexta, 7h30 às 17h18',
        salario: 'A combinar',
        idade: '18 a 65 anos',
        escolaridade: 'Ensino fundamental completo (ensino médio desejável)',
        requisitos: 'não é necessário',
        beneficios: 'Uniforme e EPIs fornecidos pela empresa',
        topicos:[
          {descricao: '- Realizar limpeza e manutenção de áreas internas e externas da empresa'},
          {descricao: '- Auxiliar na organização de materiais e equipamentos'},
          {descricao: '- Coletar e descartar resíduos de acordo com as normas ambientais'},
          {descricao: '- Seguir normas de segurança e higiene no ambiente de trabalho'},
          {descricao: '- Colaborar com a equipe para garantir um ambiente limpo e seguro'}
        ] },
    ];
    return vagas;
}
